#! /usr/bin/env bash

set -e

USERNAME="casperlabs"
DIRECTORY="/etc/${USERNAME}"

if id -u ${USERNAME} >/dev/null 2>&1; then
    echo "User ${USERNAME} already exists."
else
    adduser --no-create-home --group --system ${USERNAME}
fi

if [ -d ${DIRECTORY} ] ; then
    echo "Directory ${DIRECTORY} already exists."
else
    mkdir -p ${DIRECTORY}
    chown -R ${USERNAME}:${USERNAME} ${DIRECTORY}
fi

systemctl enable casperlabs-engine-grpc-server.service
