[package]
name = "err-standard-payment"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>", "Srinivas Reddy Thatiparthy <srini@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "err_standard_payment"

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { path = "../../../execution-engine/contract-ffi", package = "casperlabs-contract-ffi" }
