{
 "title": "Block Gossiping",
 "description": "Block propagation with the GossipService",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deploys Received",
   "type": "graph",
   "description": "Deploys sent to the API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_casper_block_api_deploys_success_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "graph",
   "description": "Blocks created by the node.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_casper_block_api_create_blocks_success_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Inserted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_dag_storage_file_insert_total) by (instance)"
    }
   ]
  },
  {
   "title": "Blocks Downloaded",
   "type": "graph",
   "description": "The bootstrap will have 1 less because it doesn't need to download the Genesis. Nobody downloads the blocks they propose.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_comm_gossiping_DownloadManager_downloads_succeeded_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sync Traversal Efficiency",
   "type": "graph",
   "description": "Shows the overhead of block summaries traversed during syncs vs the block downloads.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_comm_gossiping_DownloadManager_downloads_succeeded_total / casperlabs_comm_gossiping_Synchronizer_summaries_traversed_total) by (instance) ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(casperlabs_comm_gossiping_DownloadManager_downloads_succeeded_total) / sum(casperlabs_comm_gossiping_Synchronizer_summaries_traversed_total)",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Notification Efficiency",
   "type": "graph",
   "description": "Blocks Downloaded per Notifications Received",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_comm_gossiping_DownloadManager_downloads_succeeded_total / casperlabs_comm_grpc_GossipService_NewBlocks_requests_total) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(casperlabs_comm_gossiping_DownloadManager_downloads_succeeded_total) / sum(casperlabs_comm_grpc_GossipService_NewBlocks_requests_total)",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Relay Acceptance Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(casperlabs_comm_gossiping_Relaying_relay_accepted_total) by (instance)) / (sum(casperlabs_comm_gossiping_Relaying_relay_accepted_total + casperlabs_comm_gossiping_Relaying_relay_rejected_total) by (instance))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(casperlabs_comm_gossiping_Relaying_relay_accepted_total) / sum(casperlabs_comm_gossiping_Relaying_relay_accepted_total + casperlabs_comm_gossiping_Relaying_relay_rejected_total)",
     "legendFormat": "Overall"
    }
   ]
  }
 ]
}