{
 "title": "Highway",
 "time": { "from": "2020-03-10T12:19:04.643Z", "to": "2020-03-10T12:52:50.450Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(casperlabs_dag_storage_sqlite_insert_total, instance)"
   },
   {
    "name": "percentile",
    "query": "'0.95', '0.9', '0.85', '0.8', '0.75', '0.7', '0.5'"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages created total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(casperlabs_casper_highway_EraSupervisor_created_lambda_message_total{instance =~ \"$node\"})",
       "legendFormat": "lambda message"
      },
      {
       "expr": "sum(casperlabs_casper_highway_EraSupervisor_created_lambda_response_total{instance =~ \"$node\"})",
       "legendFormat": "lambda response"
      },
      {
       "expr": "sum(casperlabs_casper_highway_EraSupervisor_created_omega_message_total{instance =~ \"$node\"})",
       "legendFormat": "omega message"
      }
     ]
    },
    {
     "title": "Scheduled items total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "casperlabs_casper_highway_EraSupervisor_scheduled_items{instance =~ \"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Era supervisor - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node" },
  {
   "title": "Scheduled items queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "casperlabs_casper_highway_EraSupervisor_scheduled_items{instance =~ \"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "casperlabs_casper_highway_EraSupervisor_created_lambda_message_total{instance =~ \"$node\"}",
     "legendFormat": "lambda message"
    },
    {
     "expr": "casperlabs_casper_highway_EraSupervisor_created_lambda_response_total{instance =~ \"$node\"}",
     "legendFormat": "lambda response"
    },
    {
     "expr": "casperlabs_casper_highway_EraSupervisor_created_omega_message_total{instance =~ \"$node\"}",
     "legendFormat": "omega message"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Validate and add incoming block - average times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(casperlabs_casper_highway_EraSupervisor_incoming_validateAndAddBlock_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraSupervisor_incoming_validateAndAddBlock_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "validateAndAdd"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraSupervisor_incoming_effectsAfterAdded_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraSupervisor_incoming_effectsAfterAdded_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "effectsAfterAdded"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraSupervisor_incoming_propagateLatestMessage_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraSupervisor_incoming_propagateLatestMessage_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "propagateLatestMessage"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraSupervisor_incoming_handleMessage_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraSupervisor_incoming_handleMessage_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "handleMessage"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraSupervisor_incoming_handleEvents_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraSupervisor_incoming_handleEventsseconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "handleEvents"
    }
   ]
  },
  {
   "title": "Schedule average times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(casperlabs_casper_highway_EraSupervisor_schedule_handleAgenda_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraSupervisor_schedule_handleAgenda_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "handle agenda"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraSupervisor_schedule_handleEvents_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraSupervisor_schedule_handleEvents_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "handle events"
    }
   ]
  },
  {
   "title": "Schedule Agenda errors",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(casperlabs_casper_highway_EraSupervisor_schedule_errors_total{instance =~ \"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Justifications distances",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(casperlabs_casper_highway_EraRuntime_justificationsJRankDistances_bucket{instance =~ \"$node\"}[30s])) by (le))",
     "legendFormat": "JRank distance to new block"
    }
   ]
  },
  { "title": "Era runtime - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "node" },
  {
   "title": "Lambda message average timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_lambda_forkchoice_seconds_sum{instance =~ \"$node\"}[2m]) / rate(casperlabs_casper_highway_EraRuntime_lambda_forkchoice_seconds_count{instance =~ \"$node\"}[2m])",
     "legendFormat": "forkchoice"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_lambda_block_seconds_sum{instance =~ \"$node\"}[2m]) / rate(casperlabs_casper_highway_EraRuntime_lambda_block_seconds_count{instance =~ \"$node\"}[2m])",
     "legendFormat": "create block"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_lambda_ballot_seconds_sum{instance =~ \"$node\"}[2m]) / rate(casperlabs_casper_highway_EraRuntime_lambda_ballot_seconds_count{instance =~ \"$node\"}[2m])",
     "legendFormat": "create ballot"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_create_lambda_seconds_sum{instance =~ \"$node\"}[2m]) / rate(casperlabs_casper_highway_EraRuntime_create_lambda_seconds_count{instance =~ \"$node\"}[2m])",
     "legendFormat": "create lambda"
    }
   ]
  },
  {
   "title": "Lambda response average timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_response_forkchoice_seconds_sum{instance =~ \"$node\"}[5m]) / rate(casperlabs_casper_highway_EraRuntime_response_forkchoice_seconds_count{instance =~ \"$node\"}[5m])",
     "legendFormat": "forkchoice"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_response_ballot_seconds_sum{instance =~ \"$node\"}[5m]) / rate(casperlabs_casper_highway_EraRuntime_response_ballot_seconds_count{instance =~ \"$node\"}[5m])",
     "legendFormat": "create ballot"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_create_response_seconds_sum{instance =~ \"$node\"}[5m]) / rate(casperlabs_casper_highway_EraRuntime_create_response_seconds_count{instance =~ \"$node\"}[5m])",
     "legendFormat": "create lambda response"
    }
   ]
  },
  {
   "title": "Omega message average timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_omega_forkchoice_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraRuntime_omega_forkchoice_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "fork choice"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_omega_ballot_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraRuntime_omega_ballot_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "construct ballot"
    },
    {
     "expr": "rate(casperlabs_casper_highway_EraRuntime_create_omega_seconds_sum{instance =~ \"$node\"}[30s]) / rate(casperlabs_casper_highway_EraRuntime_create_omega_seconds_count{instance =~ \"$node\"}[30s])",
     "legendFormat": "create omega"
    }
   ]
  }
 ]
}