branches:
  - dev
  - master
  - release-*
  - testing*

# Common parts

# FYI: There's no merging of arrays in YAML. At least not in the Go library
# Drone uses to parse YAML. So if you mix in &sbtenv and want to add
# additional volumes, as in package step, you need to specify all volumes.

__buildenv: &buildenv
  image: casperlabs/buildenv:latest

__sbtenv: &sbtenv
  <<: *buildenv
  environment:
    - _JAVA_OPTIONS=-Xms2G -Xmx4G -XX:MaxMetaspaceSize=1G
  volumes:
    - /var/cache/cl-build/.sbt:/root/.sbt
    - /var/cache/cl-build/.ivy2:/root/.ivy2

# Build definition

clone:
  git-clone:
    image: casperlabs/buildenv:latest
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
pipeline:

  # pr

  sbt-update:
    <<: *sbtenv
    commands:
      - sbt update

  compile:
    <<: *sbtenv
    commands:
      - sbt compile test:compile doc

  compile-rust-engine:
    <<: *buildenv
    group: rust
    commands:
      - cd execution-engine/engine
      - ~/.cargo/bin/cargo update
      - ~/.cargo/bin/cargo build

  compile-rust-comm:
    <<: *buildenv
    group: rust
    commands:
      - cd execution-engine/comm
      - ~/.cargo/bin/cargo update
      - ~/.cargo/bin/cargo build

  run-rust-tests:
    <<: *buildenv
    group: test
    commands:
      - cd execution-engine/tests
      - ~/.cargo/bin/cargo test

  run-unit-tests:
    <<: *sbtenv
    group: test
    commands:
      - sbt test

  docker-build-node-and-client:
    <<: *sbtenv
    commands:
      - sbt node/docker:publishLocal client/docker:publishLocal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  run-integration-tests:
    <<: *sbtenv
    commands:
      - python3 -m pip install pipenv dataclasses typing_extensions
      - cd integration-testing
      - ./run_tests.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  # push

  package-client-deb-universal:
    <<: *sbtenv
    commands:
      - sbt client/debian:packageBin client/universal:packageZipTarball
      - mkdir -p /artifacts/${DRONE_BRANCH}
      - cp client/target/casperlabs-client_*_all.deb client/target/universal/*.tgz /artifacts/${DRONE_BRANCH}
    volumes:
      - /var/cache/cl-build/.sbt:/root/.sbt
      - /var/cache/cl-build/.ivy2:/root/.ivy2
      - /var/run/docker.sock:/var/run/docker.sock
      - /artifacts/:/artifacts/
    when:
      event: [ push, tag ]

  package-client-rpm:
    <<: *sbtenv
    commands:
      - env JAVAC_VERSION=1.8 sbt clean compile doc client/rpm:packageBin
      - mkdir -p /artifacts/${DRONE_BRANCH}
      - cp client/target/rpm/RPMS/noarch/casperlabs-client-*.noarch.rpm /artifacts/${DRONE_BRANCH}
    volumes:
      - /var/cache/cl-build/.sbt:/root/.sbt
      - /var/cache/cl-build/.ivy2:/root/.ivy2
      - /artifacts/:/artifacts/
    when:
      event: [ push, tag ]

  package-node-deb-universal:
    <<: *sbtenv
    commands:
      - sbt node/debian:packageBin node/universal:packageZipTarball
      - mkdir -p /artifacts/${DRONE_BRANCH}
      - cp node/target/casperlabs-node_*_all.deb node/target/universal/*.tgz /artifacts/${DRONE_BRANCH}
    volumes:
      - /var/cache/cl-build/.sbt:/root/.sbt
      - /var/cache/cl-build/.ivy2:/root/.ivy2
      - /var/run/docker.sock:/var/run/docker.sock
      - /artifacts/:/artifacts/
    when:
      event: [ push, tag ]

  package-node-rpm:
    <<: *sbtenv
    commands:
      - env JAVAC_VERSION=1.8 sbt clean compile doc node/rpm:packageBin
      - mkdir -p /artifacts/${DRONE_BRANCH}
      - cp node/target/rpm/RPMS/noarch/casperlabs-node-*.noarch.rpm /artifacts/${DRONE_BRANCH}
    volumes:
      - /var/cache/cl-build/.sbt:/root/.sbt
      - /var/cache/cl-build/.ivy2:/root/.ivy2
      - /artifacts/:/artifacts/
    when:
      event: [ push, tag ]


  cleanup:
    <<: *sbtenv
    commands:
      - docker images | grep none | awk '{print $3;}' | xargs docker rmi || true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [ failure, success ]


  notify:
    image: plugins/slack
    channel: alerts
    secrets: [ slack_webhook ]
    when:
      status: [ failure ]
