branches:
  - dev
  - master
  - release-*
  - testing*

# Common parts

# FYI: There's no merging of arrays in YAML. At least not in the Go library
# Drone uses to parse YAML. So if you mix in &sbtenv and want to add
# additional volumes, as in package step, you need to specify all volumes.

__buildenv: &buildenv
  image: casperlabs/buildenv:latest

__sbtenv: &sbtenv
  <<: *buildenv
  environment:
    - _JAVA_OPTIONS=-Xms2G -Xmx4G -XX:MaxMetaspaceSize=1G
  volumes:
    - /var/cache/cl-build/.sbt:/root/.sbt
    - /var/cache/cl-build/.ivy2:/root/.ivy2

# Build definition

clone:
  git-clone:
    image: casperlabs/buildenv:latest
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
pipeline:

  # pr

  sbt-update:
    <<: *sbtenv
    commands:
      - sbt update

  compile:
    <<: *sbtenv
    commands:
      - sbt compile test:compile doc

  compile-rust-engine:
    <<: *buildenv
    commands:
      - cd execution-engine/engine
      - ~/.cargo/bin/cargo build

  compile-rust-comm:
    <<: *buildenv
    commands:
      - cd execution-engine/comm
      - ~/.cargo/bin/cargo run --bin grpc-protoc
      - ~/.cargo/bin/cargo build

  run-rust-tests:
    <<: *buildenv
    commands:
      - cd execution-engine/tests
      - ~/.cargo/bin/cargo test

  run-unit-tests:
    <<: *sbtenv
    commands:
      - sbt test
      
  docker-build-node:
    <<: *sbtenv
    commands:
      - sbt node/docker:publishLocal
    volumes:
      - /var/cache/cl-build/.sbt:/root/.sbt
      - /var/cache/cl-build/.ivy2:/root/.ivy2
      - /var/run/docker.sock:/var/run/docker.sock

  run-integration-tests:
    <<: *buildenv
    commands:
      - python3 -m pip install pipenv dataclasses typing_extensions
      - cd integration-testing
      - ./run_tests.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # push

  package:
    <<: *sbtenv
    commands:
      - sbt node/debian:packageBin node/universal:packageZipTarball
      - mkdir -p /artifacts/${DRONE_BRANCH}
      - cp node/target/node_*_all.deb node/target/universal/*.tgz /artifacts/${DRONE_BRANCH}
    volumes:
      - /var/cache/cl-build/.sbt:/root/.sbt
      - /var/cache/cl-build/.ivy2:/root/.ivy2
      - /var/run/docker.sock:/var/run/docker.sock
      - /artifacts/:/artifacts/
    when:
      event: [ push, tag ]

  package-rpm:
    <<: *sbtenv
    commands:
      - env JAVAC_VERSION=1.8 sbt clean compile doc node/rpm:packageBin
      - mkdir -p /artifacts/${DRONE_BRANCH}
      - cp node/target/rpm/RPMS/noarch/node-*.noarch.rpm /artifacts/${DRONE_BRANCH}
    volumes:
      - /var/cache/cl-build/.sbt:/root/.sbt
      - /var/cache/cl-build/.ivy2:/root/.ivy2
      - /artifacts/:/artifacts/
    when:
      event: [ push, tag ]

  notify:
    image: plugins/slack
    channel: alerts
    secrets: [ slack_webhook ]
    when:
      status: [ failure ]
