[package]
name = "test-subcall-revert-call"
version = "0.1.0"
authors = ["Piotr Kuchta <piotr@casperlabs.io>"]
edition = "2018"

[lib]
name = "test_subcall_revert_call"
crate-type = ["cdylib"]

[dependencies]
contract-ffi = {package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }
