[package]
name = "named-purse-payment"
version = "0.1.0"
authors = ["Ed Hastings <ed@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
