from .common import KeyPair


PREGENERATED_KEYPAIRS = [
    KeyPair(
        private_key="MTknwWlKu58K88DWWplfjPYCv8tqTG6sZpGBQiyWw3k",
        public_key="BZTeAjALYy7++jhYjMc5Q9BD4UL/UwfFnfQS1qTKNyI",
    ),
    KeyPair(
        private_key="UAhu54gXIXX6BYdXJeQPNoZpOu0D/J8i9k3nEgUBBus",
        public_key="0Y2DEzfzGeur4T1X+qeW3r4jVGYFO7IEDSX6NGtzgi4",
    ),
    KeyPair(
        private_key="RUUsQHuJ5NT8vbrWhSVUCNDTdsmUrhQw1NrNfRLMbCQ",
        public_key="PWbu1sZBNKGqih47RO/LK0N7+k2fKCKcxV2B4ZgLa4w",
    ),
    KeyPair(
        private_key="HdzXB/zbeHwVx+nbkE08mYEhZ6tohqdBOk9V9is/MRs",
        public_key="WEx6qIFiRaJgA6mGy92orFgQ0nzVZrJUJX3Vgta419U",
    ),
    KeyPair(
        private_key="A8ByFHQBUg+qCMQGzex1RBf1EbLXZcZuIy7ESGO6gdo",
        public_key="KNf618vVHvDaxgKnY6qb2H5Ae3C49k6QJRn/MU1rY7U",
    ),
    KeyPair(
        private_key="9sL9BK1Qk4s/W31FU6spFIFkG6VuBNMoVh7xhIFDEh8",
        public_key="/w/8Gnb2TIT1bWU8g8NoPSFmXtqxlWJTEkjvejkqsmc",
    ),
    KeyPair(
        private_key="f19dthLTRgg3ZsgLpzvq688d0K2GnYVcJqt8VllP+jc",
        public_key="3oLmfxvttvo/NCaUHT3qRzrJTFz943Qe2giu96M4GIo",
    ),
    KeyPair(
        private_key="Orn2pIeP0WpomKLUJYnLeG0vEMZFGZVhjheJ+VJk4Ys",
        public_key="9w18qg8UIe2mln13Usb226uStc+lLg7SoBHfSF7ql10",
    ),
    KeyPair(
        private_key="UvTzLaA8+PqbOK06R59uBPwZJbJluS7+4IudppCHTD0",
        public_key="Ytxf6qfbbwli4B62Qz2W9lrSJmiar+/NCL+bHfgMMfk",
    ),
    KeyPair(
        private_key="wCgI5XY8l8UWCMsAn3j01nVppEvcMIwcodeImJZTkU4",
        public_key="fckFyY7wdrBG7BYK0K+O3xd0yQ7jpqtKWKHFJzzYFpM",
    ),
    KeyPair(
        private_key="zTSqJCesp7/4gh4sJKaIJSwNYjNF7SJk5hEGe2qHylI",
        public_key="cbqNIHKWT6QnlNJ1Lh/arESKJdiUMAW0xxKHSNhVIZs",
    ),
    # KeyPair(private_key="0sKoyNr+NCjFzO6P1iuLTEj/z3esIoRjkP/6yfZbQQg",
    #         public_key="mGxQGH2MPma7ilV1CPPXdH1RySCC7mfxC93Jv/QCBNA"),
    # KeyPair(private_key="u6eVDYh5kLbuIKeRCDjKwHw4Sjjig6JFoeY/p3n1Aiw",
    #         public_key="layIGurJkUWbE1puBv17gi7bXYx75SamA/6LPUn/Tck"),
    # KeyPair(private_key="lyZINj9H/GY3xsidBarhVThrexBnNDVWeBFvpcuHKHA",
    #         public_key="YihneQzeMAc/pFsjBNsM30VVxF9byuBkeYkI7IBaVe4"),
    # KeyPair(private_key="9Mm/yMmjdRsvyDbTyS7D+8RquSC6Yqy0+kh3otDqXJI",
    #         public_key="MxCWRzo/jv8LN3ARALAyUZYtBrre3WSuSKFcEvTJjUo"),
    # KeyPair(private_key="c9hdVnrTmcukvVzvXbyJt1HoUIq870wLyfQg7yTWlUc",
    #         public_key="rYhPBFOFi21YSITdm79R8G+orGuM22kSzDLyGVNi2cY"),
    # KeyPair(private_key="7EKykkVcEFg9S2qwuqBJQHCyoPoC7/lmfl8qWRU93LQ",
    #         public_key="iLX4DRpqb6jIMd1bgYL+a9GRtzBGzXAZGPxkAcsTjP0"),
    # KeyPair(private_key="Ijk+zooN/1UkC+mzWxz/a5TMcBLpYKesLsCAotl+vdQ",
    #         public_key="ehix0V+TU1vQm+jE8g0dratbFRc+WIFld46qto6v/Mg"),
    # KeyPair(private_key="dKZbVJwWnJY2GmveJZOT2UhztjtkzUj/zTeSbxw0fqA",
    #         public_key="vCYFXbBZ/NsHN3lWlqGwARjOUHXPB6UL5gxqxIctnm8"),
    # KeyPair(private_key="9Jjl/bpMiO6M/GZkRC9sOkAyrrKlmNRINbWafgBU2z4",
    #         public_key="a2tpve6WY8lfX1eqXCXaii4NJHh/cnGN60w9Kb7r8SY"),
    # KeyPair(private_key="QGBRg2Lk6c43CIRtiZ7dRIC7PMKqG5nONmni+pZQ5hc",
    #         public_key="4yPHYedGc4Iid8x9dXolZX3YkBZLnwgj4IEY3Tn2CU8"),
    # KeyPair(private_key="g5Kl6wYc74TQtlG4iGLqThiZDUbe8Jv873Sv1B9SNO8",
    #         public_key="e9BlpbdVtVQpN9c2zf90ueMhgKxJiticuSkSmC/zv1I"),
    # KeyPair(private_key="JZWKyItvc6RHXRxPwUCwjAmEcc4RaLMJOsS/vXydl2E",
    #         public_key="EXnFdI6CZc/R3Lo8HqBkCLhJSRE+QtXbyXgJHHQdFNs"),
    # KeyPair(private_key="DBABCV6noLQ00jIz/B3waHDLyp+RYGU2K+MksBIzbRw",
    #         public_key="FRgvqE4Q6zwVu33S3ZGtMsSvl3a2t5XBfiizZ2leD60"),
    # KeyPair(private_key="f0qpFpbOOuDvJM9XpnVyOdJEOGQoOpCzk9MoVAJiXvk",
    #         public_key="6gIEf7A2N+71+U9xDAavJt1ljl+vpsOW+AyIXiKmW/o"),
    # KeyPair(private_key="0wEymEGE9ZqCwQ4UlsJegKjMUFrMpI3FmKAnWZaomJk",
    #         public_key="tn62/59Q5VBOv5CSuvBG9g0Q2+wycvHRC2Ab73nwCXM"),
    # KeyPair(private_key="LzFX5MZ2dSsNQ4OQBCTWTe9e2ihfYYI+q4mhoGZxqHc",
    #         public_key="V7rwyYP0QbwtNuzSxzWCrVcae3Ny/MH49i3rEJOYJ2Y"),
    # KeyPair(private_key="ru0iJ8Hzyjl4eDxt/ixmyjoDnk23nO3wzXyeIb/H+FY",
    #         public_key="jFRB/YfwLCbRbME4BDHT7myvQi0bOYauul2DFe8ssBw"),
    # KeyPair(private_key="lYaS1TXmxRtOpO4wD6+Mw8ZTpi+mThsWxdvQvXX7IeU",
    #         public_key="u50PaTl8+NbrAnM1EtsI0KwImv569SWD5/cjVGUOdfI"),
    # KeyPair(private_key="c1Aev9YXM216LzYTbzowLr0Er7YHNAILUoh04KPX0YY",
    #         public_key="6ytpJaYmluh2ZmNj/cBSBw4VgUFzU5F52Y5HpPaaCTg"),
    # KeyPair(private_key="n+/N4fiDq2DKtY9Peo85p7hh2aPSuA6T91v9FTjq5iA",
    #         public_key="ZMHDnseBSk+TjS+HgI1Uos17CAjptPH6vgQvYseJkp4"),
    # KeyPair(private_key="FjGIaRAdEXZIxxg8oOw0fk8KC4lRBQru61DeY+yDYQE",
    #         public_key="HFZhv374qZY7mafr6inlGf6Lr+3UoqDzE9+BkbaTkTE"),
    # KeyPair(private_key="GNTu4t3DDz0rlzYGLGb/gu0A4UaBYgV1qLq+lBV8ZlE",
    #         public_key="VcypnZy9X4YpvZ/od+gKFIjgZrLbpPw/+2qliyCRex0"),
    # KeyPair(private_key="Xe/uAQCt8n3FoFlY77pEbY5IsGb/ZHT+si9+g7a7xGU",
    #         public_key="+bdJpV97LYcV0N+ErCZ0w/S0chHQjLqI3vPs4sg6j3o"),
    # KeyPair(private_key="5fD1k+FqhQjy25vrbjnV+gBrGGS6w7ccmjeWlrC3JHs",
    #         public_key="B7/J7iJUjtd2zy/4r3C9SGGUNsNR1og5/CD0uRW2dog"),
    # KeyPair(private_key="rs4exxeXDO5W/URjObyWHQS1rwaZSQEqxLd3EefNkIc",
    #         public_key="4TIfClpUgkyGpOI45RRyZHbQZrLwGUGWlaxzJA9+GJE"),
    # KeyPair(private_key="Q3W79IeVIQaNE/knrLAPnFPA1RsZegghuOaqWQ6ZPYs",
    #         public_key="fQC/PAD8Z9eA6+kVBS7KyE35eL5TviDa4uvFkUvv7r4"),
    # KeyPair(private_key="BIa/yrmk55KVYNWCGFkamLCOzp1W4wZ3IoaeFJ2iPfE",
    #         public_key="OXzv+FwnA0RkpugT2A1tlmJoejVsZcHEyVFVW9nNCiE"),
    # KeyPair(private_key="VUiidVy2NjWEqi9+eYIBHbFjNF0w2ouWvY4zbhz/aHg",
    #         public_key="NkvuzF6kYS0wnk6Ubi7rbXaBSt+SkxU19Ak98wIVRFw"),
    # KeyPair(private_key="wcjYKleSUQgvJ/3M7/Kj2XgHtsUjl4dA5dCJlYKK9To",
    #         public_key="aXamJ+zPR1lakkp8rH1WOKJ6Si1zVopGMOwXe7RmQDU"),
    # KeyPair(private_key="IQfoC47JR0p+LgwUNAN5oI5qK56nYR5zSMzCgBQPMMU",
    #         public_key="TsIgQ9kfGAZaWTIttDI3FEzCi93Tbgasp79yx90qq0g"),
    # KeyPair(private_key="2WyqjCJXVrKsTDTzuAfNYg77pfCPDNCLdFmViHNoslo",
    #         public_key="VLqPofDCKr7V1xbXNwEobN0MaM3AO1UzWaFhUn+qIA4"),
    # KeyPair(private_key="vSIl/2pw3fdr2qEyfKxvc7AqugPdS8Wl0BHRkvdoa5k",
    #         public_key="Y71QN0mLINyViqrGYgKtJWpsUesBCeH2FUqAHbzl0wE"),
    # KeyPair(private_key="64TKNZwENKldcAd4QDJCbwFRuffqjVoJnxuKwrSR+28",
    #         public_key="HvVsb3Qh/7odCN19AGLW8O+p+pI5eQvXJKNystnQ1SQ"),
    # KeyPair(private_key="ewLTyc1JZBDNoYkdOe5rTu+9hzlDOFCUZI4n2tEb/gs",
    #         public_key="WMuq5P45TGTl2SslxOsAqobMSy7F2nqIlJRSXzQDwmc"),
    # KeyPair(private_key="lZAuzEX8pekL/vuyvrvKZWGa43lFJT6ddu0B58bvYMQ",
    #         public_key="ZQY2SBbezmXEb4nPdSJjSht/Py3OxIK5EOtC5D6Ev4A"),
    # KeyPair(private_key="SOLyVHr4CqeRjboXpwIUsvmyQinjZWHzTX80WdiaQBg",
    #         public_key="cKX6Y3xO1AvbvU4ZHq7rbzG9vnsYXD1fOLYoIf2KywM"),
    # KeyPair(private_key="R7fU3tcWzI/N/MQYxZe5fUxhlvHgdzrVKE3Ms6NxRJs",
    #         public_key="sQZCxvNMkUtE8eWlrTi3OBQshVd6nsEPMleQtLkjJkk"),
    # KeyPair(private_key="iWY7NHSwmfMJq7H5kND6y7ToKFBEzFMf9vZGEQ3MgQk",
    #         public_key="zwdBRmdo7uP9cQFhQiEviMUejO1s0OV1+f84ZsxMtAg"),
    # KeyPair(private_key="Oga5aAvkvFxXIffJGLzQImyp1uZGLZzgP81QNW2jhZU",
    #         public_key="mavQoWggj8BnH5iA35mjnN3TdKNBEQSQE+j1UbWyjrA"),
    # KeyPair(private_key="wQ8XjZUkPE0XJrnksZ/KSMYurT9yhoTiLkD1ua1gZg8",
    #         public_key="qR4nvNpf8klQhB2lhhRdk0t8Q0iFhDEEdsSBRnx4HT4"),
    # KeyPair(private_key="XgH0EcJy4IPIiZeTMIzuGxDpdmRX35/x7Gj9i5qT31E",
    #         public_key="3YqW+cGHg3rVQeuENCwwDf5Y/gp6VWmQDpAScA8qqTQ"),
    # KeyPair(private_key="7geba2gihzQTMyz3805NVaeLrxtdbXlD7xVKBHTXWOQ",
    #         public_key="PceG1JCoHpKc/YaM1WaYf8vqXEWuKHSvWJOJTTNTy9w"),
    # KeyPair(private_key="tf2ElDcI8PD4+ynyDp6xxGfP6e4erkBTeBIGbPq24og",
    #         public_key="wyNQzJm5pO2sAxLzYyULwCgDBDr8F+bA+Gpmcvsojuk"),
    # KeyPair(private_key="5Bmhf+UXsxEUdvlEGz9iUOiMPQJuGqNY1sJBrsSMLbc",
    #         public_key="4MTaf3B5fMhuUda0MYg44UWH9qMWUzwFDphwjFx1oc0"),
    # KeyPair(private_key="Ioeon+tJO6eU7cNU1JM0m58wpHDn27b1sbj6EqF7smI",
    #         public_key="62nSidthZN4kaOxsRn8Qeq0x6UoDwWXE7p4yAc+G4AA"),
    # KeyPair(private_key="lh21UE1CSa2G4LUD8px1LsjZfp7pjKLMRdNpxG02NXw",
    #         public_key="Tn2wIaXaRiKHBvarROlqqsEY88LEfgOsSfc4W21hMEE"),
    # KeyPair(private_key="ApFZG7pXhhIiPop+nhAA++ryzZhEnMAuLIlfZ/TbhPQ",
    #         public_key="A3/pDHUCfCFD4kCO7O9fRuUQtPFn46Zp0OltR0XUZqE"),
    # KeyPair(private_key="+72WWdQ00CzbBOnlsqMPvGB0RYq5TYJeX5ELVS6zrug",
    #         public_key="KBiSEK8Citx3UWYy4UrgUnjom9rQOS6MissH6ic3I50"),
    # KeyPair(private_key="Yy2jpPdAdzmiUs9lcUZKpJ6qThw2kJi0keF/L+Il4Xg",
    #         public_key="awYLnY0SDjHaP1e4G5ZAxGQaSllm17VxGT/m5f/hHVY"),
    # KeyPair(private_key="jqNFoH/jXz3pRXhRLtesjj+Z7NCX2dGA3GK4ASTiHCc",
    #         public_key="cJb4vaUSuSk1FrbrR539Bj2K4gjj3lil0y38o+r7pmU"),
    # KeyPair(private_key="noYpkzIFijuxDo1VmXT4X/CphucPOUQzRKHzZPCk+WU",
    #         public_key="OqGLtsYEhupB8N12GIdp3Q1F/dNWEdZ6VyVcQZ6srxA"),
    # KeyPair(private_key="FDH37ABw76cdNEO4HT0JkxUBMgooxllDtaWSzlvtekE",
    #         public_key="C2+3dCra78cgZggwS+SxP30P+jM2SvNJ8zbXUC3ZDRs"),
    # KeyPair(private_key="IRu/GJ79av/QWmSVCBeOQzujGZrshsIgT0rUwpE7lGQ",
    #         public_key="2ExxfxAMhvm3MMOkGIgpn3kGS98oYzv9w+Resxwevos"),
    # KeyPair(private_key="DmR/dTRDXMqQ62xFpldaYgjdl9XXSP2CZTE+BGSFDbU",
    #         public_key="P9nkDPSI9HmCriLMNXwqaq8r9qKspwfI+iva/TtPUeI"),
    # KeyPair(private_key="4MVjjRqViX8P8xeP6mVN5HGHZhKsEbr4ucGKITeSFsg",
    #         public_key="VW9zuUJJS0/YAMrUNtIjM0/Xe8uqieNUXV2YlzTUUD4"),
    # KeyPair(private_key="gyFu36ioMAUh/74srL79LCnI8bQ5BmMGEsE8XoBh7fg",
    #         public_key="uS3ue6VehAncs3znA5pz7RBBdCK19uakYbG9iD74xRE"),
    # KeyPair(private_key="CuMdiU0OR+UffIo0cfwEkF+jJzbCwepv/VqpEZMo5gA",
    #         public_key="xPDInjJrLMoXFMEt87yYqREmNZK6EJVfm1iuWYQBbJQ"),
    # KeyPair(private_key="+hr/yinX2idSHvWAlJ08Mld1YdGq8MF0ffP+a7+tdqE",
    #         public_key="yIucMigizJ+cjmf0oN6sMUB8QmJLrnkqv2jGCJHKGtM"),
    # KeyPair(private_key="TvEncUE99zENxcnlvAIu5BcqK/SjAI8a5e+j3HZf80g",
    #         public_key="3KrrF0PjfhJDDAB5kp5rT+h+dZW1u1PTKHaOS1BpV48"),
    # KeyPair(private_key="jnGDy8HWztWXrlz9c3vGQ2PK6IMFJ5ajUbSwrHue0DU",
    #         public_key="N12owg5Q5qQRCeFDr8raTsmj4Q+XScrGw+XgDTYpzc0"),
    # KeyPair(private_key="n2CVlMBhZf+UU7UQrBqNm8rNImO/+/grpXcuYK4Kfxs",
    #         public_key="5B5PoFfcMX8/T+irBYk1CEeLtOOd3BCxyYAXKQx2XJU"),
    # KeyPair(private_key="IoPmbjLPUrTm0hxaski7aG6kvRd+yYlghGxB1GmJBlk",
    #         public_key="0FrOBu9nE/+tut+FpAdZAP7AWcmkTp+5LOKVON5HoBs"),
    # KeyPair(private_key="CB+D4voD/dKB5Qn6fyMgEVX+WIoQz1qa/9CcIV1oszk",
    #         public_key="NGH/ChkY9pWxgk+d0YYoQLn7REkzsTaxYK1tCPuf188"),
    # KeyPair(private_key="4KRyyFUX0Q5nzBNtjKKdItXNRcZ6zAn1Bn18ZWkO4t8",
    #         public_key="nWCmTb1MbGq6WTAQhYM2iVyHrf0pwK2z8Yt+5QainJk"),
    # KeyPair(private_key="4qHEC7IzdsZTwrcxEAHx5n2LbhWMKMFLkOVb5hfavl4",
    #         public_key="78YoXhKJ6J2q7n219FHy7e4EVzoTz6StL0dyMma1DiE"),
    # KeyPair(private_key="yAup0pHURYCSDPJ9mwmsBSzPG1ObMaMg0M2nNa0lOCE",
    #         public_key="vRqss8zUC7aGvYPXMuUE9JwnaOR0V9T1UhlOffn1l7g"),
    # KeyPair(private_key="B9K668f7+fOBYBhVsyRDRVUiFvu85E5ST2ixS6Qn/L4",
    #         public_key="9We5BJoSe9u+ZGQH62JEoed64b+tGfQIjBUJyVf6ypA"),
    # KeyPair(private_key="SgCJ/FrVmKvM4QbQw1zvuhnKXd/zO50JXeDxJe6Cynk",
    #         public_key="aUs8yd0Ewk2ydoV/qw2PKxgPqNmw0KzGsDwSbomEVvw"),
    # KeyPair(private_key="MM8jufalI/KpJMfZN+exhcHJR9LCPEcfXxWoM0aF3HA",
    #         public_key="+PQ3Wyf7UBbKdYjerJMwUldItf3hWDGK8Sw8mUs/qYY"),
    # KeyPair(private_key="3KaxCcBxmikllkUYiRSICwYgLA4sdDIjNIrbnuXM0Pw",
    #         public_key="8wymCPaiQPTe44LL7Dpk7joPLFx1ESlnkOfI+vWQLt8"),
    # KeyPair(private_key="jqTUlQhQ1ORCvoffcGH6D0Ew3lZ/1sIkuMim9dOuFsQ",
    #         public_key="3tnAyHGrj830GrxnT+vDr8473yBjINCRLeMwQaUfG3o"),
    # KeyPair(private_key="63Q1zpmrtdPRyHXIs+EwYfCkeBC+pyuNuUs5S8er2d0",
    #         public_key="fBEOhQBRXGig1+9juAV+k9riHvsazWs42Bhh2DVsf5E"),
    # KeyPair(private_key="1LlIpl3J9h4LOPCAlDL0x37nDlU0Tb6kZAJckk9wInM",
    #         public_key="3wLZ/sYYPpG9XC8wrNLujsWCL3GXFWPJVKXQdeuRKHE"),
    # KeyPair(private_key="KodBcwv2TZaR1pYgxsPA2wNf8YY9WH9gQlowAV0olsI",
    #         public_key="nRjKxo2Jj0YnfETAP8UrpN4f4eyBwUPTnUKJEec6awo"),
    # KeyPair(private_key="g7luHOq5ptpqRyCxinR/aydM3eO5EsbLE/Uy/xTNzZg",
    #         public_key="Qhb7nmNaw49cHU8GyZ/pS/t4KIIarZWF3jZ87VF3QFE"),
    # KeyPair(private_key="Ww3Z8o0ghotwTNX7MJ20SOZXx+jqpea7LVNY/oLFEPk",
    #         public_key="SuwUniE4lHYsSWgdpghzrI0awVThS8+wRLb/d+JSfns"),
    # KeyPair(private_key="VsUBIIEifb4YzbFEaWDwsjdvUjJZtHde8wCFcYU/M78",
    #         public_key="ordtGjRFEWpvpJVcYQNN2W3cAOoAnimNvhTSjy/PbC4"),
    # KeyPair(private_key="uBWLyfbuk/950ava3qqCk2fJj1k400Gylk0bHWmuOoY",
    #         public_key="Hcaeo1kWglTH/iYBH338SfL8kkQ6fh42gWF56Geaa3s"),
    # KeyPair(private_key="lUhhmYLwe4rCsHOGY8yeDJ0djoBugkYYWaZJnM+fcZg",
    #         public_key="lr1cqlHMaTrp5ylolGdvTAil7BRt7e4aME2I22ffqPc"),
    # KeyPair(private_key="/h9M0Rv0wn1s9xd8lurXa+bQU0goWsBcajCLZh35DWY",
    #         public_key="AtO+eFzapE/Eq++OoFrTeYtY8RHIHCX2SCMCHSb94+4"),
    # KeyPair(private_key="E5Ko96cYDX4Xh8MMp9CY5fDJnBLQDhaZS1t2VslC2Sw",
    #         public_key="l662GIjKtTdVw2DPaROapy5r2lAlwiNrVzV4ljGm2a0"),
    # KeyPair(private_key="ZmMCmtM2gFNkMbfZbHFjQlXF/AHwrbd1+Ouu/GYFpgY",
    #         public_key="2V1ZIiVH0FLNRGgHIiqFNOit+9PRgiO2uynyGb28EyU"),
    # KeyPair(private_key="IuOgMpSFi76D3pi/Rf8ksYTla6WijoBFA5/SG3PeApY",
    #         public_key="i+ZGh51/KzjC7eYPdOBfL6F4yQHvhVFzcRTiHc6syNY"),
    # KeyPair(private_key="dR9M4FuionIZS38a4QvMPx2bDZknZYaRcTh6JHBkzIM",
    #         public_key="B0yE+DZ01HhluDp67RN19kUNIb3b0mCgY71ZruGXufY"),
    # KeyPair(private_key="OYhibEIrLPgkbXfYXQSHQkWN1yOu3OWjrXdpsIjHhrk",
    #         public_key="e1D3J/3X77ZH7PvNd7YJg4U3MnStd1W3GZGI0QByo88"),
    # KeyPair(private_key="pH28Wz/g5rlOgFkiCn7iBjcsqAB3j0uEdMTOesA63Y8",
    #         public_key="tP86FZH8xLC87du9O5p+RK3ZW7t0XHkdbdal9OqzCm0"),
    # KeyPair(private_key="lJ8Ttyc3R8VWB9QE+sYbaRABAWhIOCPjuOlyUwdgwbo",
    #         public_key="Jd+7StHq1yZjtqm00OTt58We3ltpfTpMDcsjg/K5ZnY"),
    # KeyPair(private_key="dPK01urLxmJizYAUM7ejCcWtpnsQgtfiBbhXDEU3Uqg",
    #         public_key="DUzh1+Wz+ipbkQnilfRznniqsv+bDpIIrmPHWhTgICQ"),
    # KeyPair(private_key="Lvg5zLd3ndSyFgqoCDR9eOH67OnGASEdF9pjBYJktG8",
    #         public_key="3p7FoU4wz3N3MeO9pioF0PS7ZResnfrQyeRH5Ou4a2o"),
]
