#! /usr/bin/env bash

set -e

# Default Variables
# ---
DEFAULT_USERNAME=casperlabs
DEFAULT_CONFIG_DIRECTORY="/etc/${DEFAULT_USERNAME}"

# Creation of Files/Directories
# ---
# Assure $DEFAULT_CONFIG_DIRECTORY is available for unpacking
if [ -d ${DEFAULT_CONFIG_DIRECTORY} ] ; then
    echo "Directory ${DEFAULT_CONFIG_DIRECTORY} already exists."
else
    mkdir -p ${DEFAULT_CONFIG_DIRECTORY}
fi
