{
 "title": "Block Broadcasting",
 "description": "Block propagation with the TransportLayer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deploys Received",
   "type": "graph",
   "description": "Deploys sent to the API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_casper_block_api_deploys_success_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "graph",
   "description": "Blocks created by the node.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_casper_block_api_create_blocks_success_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Passing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Block Passes" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_casper_packet_handler_blocks_received_total) - sum(casperlabs_casper_packet_handler_blocks_received_again_total)",
     "legendFormat": "New Block Passes"
    },
    {
     "expr": "sum(casperlabs_casper_packet_handler_blocks_received_again_total)",
     "legendFormat": "Repeated Block Passes"
    },
    {
     "expr": "1.0 - sum(casperlabs_casper_packet_handler_blocks_received_again_total) / sum(casperlabs_casper_packet_handler_blocks_received_total)",
     "legendFormat": "Efficiency"
    }
   ]
  },
  {
   "title": "Blocks on Node",
   "type": "graph",
   "description": "Number of blocks the node created or received from others, i.e. the total it knows about.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(casperlabs_casper_block_api_create_blocks_success_total + casperlabs_casper_packet_handler_blocks_received_total - casperlabs_casper_packet_handler_blocks_received_again_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}