[package]
name = "create-test-node-02"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[lib]
name = "create_test_node_02"
crate-type = ["cdylib"]

[dependencies]
create-test-node-shared = { path = "../create-test-node-shared" }
