[package]
name = "err-transfer-to-account"
version = "0.1.0"
authors = ["Joe Sacher <joe@casperlabs.io>", "Srinivas Reddy <srini@casperlabs.io>"]
edition = "2018"

[lib]
name = "err_transfer_to_account"
crate-type = ["cdylib"]

[features]
default = []
std = ["contract-ffi/std" ]

[dependencies]
contract-ffi = { path = "../../../execution-engine/contract-ffi", package = "casperlabs-contract-ffi" }
