#! /usr/bin/env bash

set -e

DEFAULT_USERNAME="casperlabs"
DEFAULT_SYSTEMD_SERVICE_FILE="/lib/systemd/system/${DEFAULT_USERNAME}-node.service"
DEFAULT_DATA_DIRECTORY="/etc/${DEFAULT_USERNAME}"
DEFAULT_TOML="${DEFAULT_DATA_DIRECTORY}/default-configuration.toml"

# Check if $DEFAULT_USERNAME user exists
if id -u ${DEFAULT_USERNAME} >/dev/null 2>&1; then
    echo "User ${DEFAULT_USERNAME} already exists."
else
    adduser --no-create-home --group --system ${DEFAULT_USERNAME}
fi

# Assure default service file has correct permissions after unpacking
if [ -f ${DEFAULT_SYSTEMD_SERVICE_FILE} ] ; then
    chmod 0644 ${DEFAULT_SYSTEMD_SERVICE_FILE}
fi

# Assure default data directory is owned by $DEFAULT_USERNAME; created in preinst
if [ -d ${DEFAULT_DATA_DIRECTORY} ] ; then
    chown ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_DATA_DIRECTORY}
fi

# Assure default toml is owned by $DEFAULT_USERNAME after unpacking
if [ -f ${DEFAULT_TOML} ] ; then
    chown ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_TOML}
fi
