#! /usr/bin/env bash

set -e

USERNAME="casperlabs"
SYSTEMD_SERVICE_FILE="/lib/systemd/system/${USERNAME}-node.service"
DEFAULT_TOML="/etc/casperlabs/default-configuration.toml"

if id -u ${USERNAME} >/dev/null 2>&1; then
    echo "User ${USERNAME} already exists."
else
    adduser --no-create-home --group --system ${USERNAME}
fi

if [ -f ${SYSTEMD_SERVICE_FILE} ] ; then
    chmod 0644 ${SYSTEMD_SERVICE_FILE}
fi

if [ -f ${DEFAULT_TOML} ] ; then
    chown ${USERNAME}:${USERNAME} ${DEFAULT_TOML}
fi
