#! /usr/bin/env bash

set -e

DEFAULT_USERNAME=casperlabs
DEFAULT_DIRECTORY="/etc/${DEFAULT_USERNAME}"

# Assure $DEFAULT_DIRECTORY is available for unpacking
if [ -d ${DEFAULT_DIRECTORY} ] ; then
    echo "Directory ${DEFAULT_DIRECTORY} already exists."
else
    mkdir -p ${DEFAULT_DIRECTORY}
fi
